const SET_LIST_POI = 'SET_LIST_POI'
const SET_LIST_POI_EN = 'SET_LIST_POI_EN'
const SET_LIST_POI_FR = 'SET_LIST_POI_FR'
const SET_CURRENT_LISTPOI_BT = 'SET_CURRENT_LISTPOI_BT'
const SET_CURRENT_LISTPOI_BT_SAVE = 'SET_CURRENT_LISTPOI_BT_SAVE'
const SET_POPUP_BT = 'SET_POPUP_BT'
export { 
    SET_LIST_POI,
    SET_LIST_POI_FR,
    SET_LIST_POI_EN,
    SET_CURRENT_LISTPOI_BT,
    SET_CURRENT_LISTPOI_BT_SAVE,
    SET_POPUP_BT }
